export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
                style={{
                  backgroundColor:"greenyellow",
                  fontSize:"10rem",
                }}
        >Header</header>
        {children}
        <footer
        style={{
          backgroundColor:"ghostwhite",
          fontSize:"10rem",
        }}
        >Footer</footer>
        </body>
    </html>
  )
}
